name: openswitch
version: '3.0.0-dev'
summary: OpenSwitch NOS Snap
description: |
  The OpenSwitch platform is an open source, Linux-based network operating 
  system (NOS) for disaggregated switches built around OCP-compliant hardware.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  openswitch:
    plugin: python
    python-version: python2
    stage-packages:
      - python-pip
    override-build: |
      snapcraftctl build
      pip install pysnmp
  opx:
    plugin: python
    python-version: python2
    stage-packages: 
      - sqlite3
      - bridge-utils
      - python-systemd
      - redis-server
      - libhiredis0.13
      - python-apt
      - python-netaddr
    source: 
      - opx/libopx-logging1_2.1.1_amd64.deb 
      - opx/libopx-common1_1.5.0_amd64.deb 
      - opx/libopx-db-sql1_1.1.1_amd64.deb 
      - opx/libopx-sai-vm1_17.1.0+opx7_amd64.deb 
      - opx/python-opx-logging_2.1.1_amd64.deb 
      - opx/libopx-cps1_3.6.2+opx5_amd64.deb 
      - opx/python-opx-cps_3.6.2+opx5_amd64.deb 
      - opx/opx-cps_3.6.2+opx5_amd64.deb 
      - opx/libopx-base-model1_3.142.0_amd64.deb 
      - opx/opx-sai-api-dev_35.1.0_amd64.deb 
      - opx/libopx-nas-common1_7.1.0_amd64.deb 
      - opx/libopx-nas-ndi1_4.5.0_amd64.deb 
      - opx/libopx-nas-qos1_2.4.0_amd64.deb 
      - opx/libopx-nas-linux1_5.19.0_amd64.deb 
      - opx/libopx-nas-l3-1_3.6.0_amd64.deb 
      - opx/libopx-nas-l2-1_1.21.0_amd64.deb 
      - opx/libopx-nas-interface1_5.18.0_amd64.deb 
      - opx/libopx-nas-acl1_2.6.0_amd64.deb 
      - opx/opx-nas-daemon_2.2.0_amd64.deb 
      - opx/opx-nas-interface_5.18.0_amd64.deb 
      - opx/opx-nas-common_7.1.0_amd64.deb 
      - opx/python-opx-snmp_1.1.0_all.deb 
      - opx/opx-alarm_1.0.2_all.deb 
      - opx/opx-tools_1.0.1_amd64.deb 
      - opx/opx-tmpctl_2.1.1_all.deb 
      - opx/opx-nas-linux_5.19.0_amd64.deb 
      - opx/opx-nas-qos_2.4.0_amd64.deb 
      - opx/opx-nas-acl_2.6.0_amd64.deb 
      - opx/opx-nas-l3_3.6.0_amd64.deb 
      - opx/opx-nas-l2_1.21.0_amd64.deb 
      - opx/libopx-sdi-sys-vm1_4.21.0_amd64.deb # Provides libopx-sdi for vms. Change for what switch you are building for.
      - opx/libopx-pas1_3.1.2_amd64.deb 
      - opx/opx-pas_3.1.2_amd64.deb 
      - opx/opx-logging_2.1.1_amd64.deb 
      - opx/opx-platform-config-dell-vm_1.4.10_all.deb 
      - opx/opx-dell-vm_1.4.10_all.deb
    source-type: deb

apps:
  opx-acl-init:
  opx-acl-persistency:
  opx-alms:
  opx-cps-db:
  opx-cps:
  opx-create-interface:
  opx-front-panel-ports:
  opx-ip:
  opx-monitor-phy-media:
  opx-nas-init:
  opx-nas:
  opx-nas-shell:
  opx-nbmgr:
  opx-pas:
  opx-phy-media-config:
  opx-pysnmp:
  opx-qos-init:
  opx-tmpctl:
  opx-vm:
  opx-vport:
  opx-vrf:

